package com.example.safodel.model

import com.ajithvgiri.searchdialog.SearchListItem
import java.util.*
import kotlin.collections.ArrayList

class SuburbList {

    /*-- init the LGA list --*/
    companion object{
        fun init(): ArrayList<SearchListItem> {
            val list = Arrays.asList(
                "Skinners Flat",
                "Hollands Landing",
                "Earlston",
                "Rockbank",
                "Prentice North",
                "Archies Creek",
                "Essendon West",
                "Magpie",
                "Oakvale",
                "Fyansford",
                "St Helens Plains",
                "Newbridge",
                "Richmond Plains",
                "Doncaster Heights",
                "Broadwater",
                "North Shore",
                "Bacchus Marsh",
                "Wollert",
                "Mitchell Park",
                "Youanmite",
                "Glenormiston South",
                "Yarraville West",
                "Rocky Point",
                "Clarkes Hill",
                "Tresco West",
                "Lavers Hill",
                "Cotswold",
                "Denicull Creek",
                "Black Rock North",
                "Kiata",
                "Ventnor",
                "Crib Point",
                "Harrietville",
                "Staceys Bridge",
                "Peechelba",
                "Airly",
                "Norong Central",
                "Nirranda South",
                "Cowa",
                "Wonwondah East",
                "Spring Hill",
                "Thornbury",
                "Knoxfield",
                "Lindenow",
                "Rosebud West",
                "Sorrento",
                "Batesford",
                "Enfield",
                "Wando Vale",
                "Murrindindi",
                "Basalt",
                "Wesburn",
                "Brooklyn",
                "Shepparton South",
                "Wye River",
                "Eaglehawk North",
                "Corryong",
                "Monomeith",
                "Gatum",
                "Bennison",
                "Licola North",
                "Melton West",
                "Bullumwaal",
                "Creek Junction",
                "Dartmouth",
                "Stoneleigh",
                "Lyndale",
                "Castleburn",
                "Moe South",
                "Warrnambool West",
                "Croydon",
                "Moornapa",
                "Robinvale Irrigation District Section D",
                "Camberwell North",
                "Murchison",
                "Kalorama",
                "Towong Upper",
                "Mildura",
                "Bushfield",
                "Nyrraby",
                "Sandford",
                "Toolong",
                "Bass",
                "Wannon",
                "Tutye",
                "Breakwater",
                "Lalalty",
                "Toora North",
                "Jancourt East",
                "Naringal East",
                "Heyfield",
                "Redan",
                "Napoleons",
                "Caulfield East",
                "Pakenham",
                "Coburg",
                "Flagstaff",
                "Watergardens",
                "Mount Slide",
                "Wooreen",
                "Tarwin",
                "Jam Jerrup",
                "Mount Eccles",
                "Flinders Naval Depot",
                "Smokey Town",
                "Crystal Creek",
                "Indented Head",
                "Merriang",
                "Moreland West",
                "Lake Moodemere",
                "Laharum",
                "Shoreham",
                "Russells Bridge",
                "The Pines",
                "Macleod",
                "Warburton",
                "Axedale",
                "Don Valley",
                "Tetoora Road",
                "Piries",
                "Mayreef",
                "Fish Point",
                "Geelong",
                "The Cove",
                "Sidonia",
                "Delegate River East",
                "Leongatha South",
                "Mandurang",
                "Sutherland",
                "Tarranyurk",
                "Pheasant Creek",
                "Chadstone",
                "Nar Nar Goon North",
                "St Arnaud North",
                "Mincha West",
                "Strathewen",
                "Seville",
                "Nurrabiel",
                "Laverton North",
                "Queensferry",
                "Kyabram South",
                "Karingal",
                "Vermont South",
                "Junction Village",
                "Loddon Vale",
                "Ringwood East",
                "Huntly North",
                "Murgheboluc",
                "Toolern Vale",
                "Central Park",
                "Lucyvale",
                "Eaglemont",
                "Dunneworthy",
                "Streatham",
                "Skenes Creek North",
                "Mckinnon",
                "Mooroopna North",
                "Lancefield",
                "Waubra",
                "Kyabram",
                "Langley",
                "Miowera",
                "Chute",
                "Lal Lal",
                "Tarrawingee",
                "Chadstone Centre",
                "Seaspray",
                "Meadow Heights",
                "Kings Park",
                "Drouin East",
                "Halls Gap",
                "Arapiles",
                "Cardigan",
                "Tallangatta Valley",
                "Nhill",
                "Joel South",
                "Reservoir East",
                "Epping",
                "Cobains",
                "Lawrence",
                "Wandiligong",
                "Campbells Creek",
                "Keon Park",
                "Shirley",
                "Holmesglen",
                "Aireys Inlet",
                "Whitfield",
                "Collingwood",
                "Kanagulk",
                "Clifton Hill",
                "Flowerdale",
                "Aspendale Gardens",
                "Wurruk",
                "Kingston",
                "Aberfeldie",
                "Stradbroke Park",
                "Roslynmead",
                "Deep Lead",
                "Myola East",
                "Tarrone",
                "Cobaw",
                "Yarra Glen",
                "Blind Bight",
                "Kilcunda",
                "Mckenzie Creek",
                "Paraparap",
                "Jeffcott",
                "Tangambalanga",
                "Carlton South",
                "Mill Park",
                "Marengo",
                "Dales Creek",
                "Balwyn North",
                "Pennyroyal",
                "Cathkin",
                "Matlock",
                "Hartwell",
                "Newham",
                "Maindample",
                "Sebastian",
                "Nap Nap Marra",
                "Smythesdale",
                "Murraydale",
                "Coonooer West",
                "Deer Park North",
                "Wandella",
                "Bruarong",
                "Seaton",
                "Frankston East",
                "Musk Vale",
                "Navarre",
                "Nirranda",
                "Brookfield",
                "Watsonia",
                "Elliminyt",
                "Lindenow South",
                "Laen",
                "Diamond Creek",
                "Panmure",
                "Maroona",
                "Mount Mitchell",
                "Byaduk",
                "Blakeville",
                "Mentone East",
                "Hawthorn East",
                "Monomak",
                "Lake Gardens",
                "Mcevoys",
                "Eumemmerring",
                "Karnak",
                "Lake Wongan",
                "Deer Park",
                "Chelsea Heights",
                "Jallukur",
                "Cranbourne East",
                "Wilkur",
                "Maffra",
                "Domain Road Po",
                "Rocklyn",
                "Robinvale Irrigation District Section B",
                "Deanside",
                "Chewton",
                "Taggerty",
                "Kirkstall",
                "Ringwood North",
                "Grand Ridge",
                "Toorloo Arm",
                "Moorabbin Airport",
                "Jarrahmond",
                "Niddrie",
                "Swan Reach",
                "Yarrawalla",
                "Pyramid Hill",
                "Berringa",
                "Huntingdale",
                "Malvern North",
                "Cosgrove South",
                "Ladys Pass",
                "Donald",
                "Riddells Creek",
                "Coldstream",
                "Lake Mundi",
                "Deptford",
                "Bundalong",
                "Murrawee",
                "Marong",
                "Swan Hill West",
                "Meering West",
                "Moondarra",
                "Exford",
                "Nillahcootie",
                "Southland Centre",
                "Hawksburn",
                "Mia Mia",
                "Balnarring",
                "Big Desert",
                "Braybrook North",
                "Denver",
                "Heathwood",
                "Broadlands",
                "Fitzroy North",
                "Heath Hill",
                "Kardella South",
                "Wheelers Hill",
                "Coolaroo",
                "Hillcrest",
                "Marionvale",
                "Canadian",
                "Pyalong",
                "Beaumaris",
                "Wellsford",
                "Melton South",
                "Elevated Plains",
                "Maryknoll",
                "Koonoomoo",
                "Shepparton",
                "Lubeck",
                "Laburnum",
                "Shepherds Flat",
                "Traynors Lagoon",
                "Katandra West",
                "Calulu",
                "Gardenvale",
                "Braeside",
                "Sandringham",
                "Narracan",
                "Airport West",
                "Sugarloaf Creek",
                "Corinella",
                "Gaffneys Creek",
                "Carnegie",
                "Riverslea",
                "Maidstone",
                "Smeaton",
                "St Clair",
                "Mallacoota",
                "Hurdle Flat",
                "Sumner",
                "Cranbourne",
                "Korumburra",
                "Jackass Flat",
                "Bushy Park",
                "Burwood",
                "Banksia Peninsula",
                "Lawloit",
                "Laen East",
                "Terang",
                "Manor Lakes",
                "Fyans Creek",
                "Summerlands",
                "Creightons Creek",
                "Naringal",
                "Jeeralang Junction",
                "Warneet",
                "Bareena",
                "Modewarre",
                "Nullawarre",
                "Steels Creek",
                "Wiseleigh",
                "Nilma",
                "Fieldstone",
                "Boorolite",
                "Traralgon",
                "Warrnambool East",
                "Point Wilson",
                "Breamlea",
                "Darraweit Guim",
                "Deer Park East",
                "Cornishtown",
                "Burnley",
                "Wallaloo",
                "Brunswick North",
                "Northland Centre",
                "Durham Lead",
                "Invermay",
                "Dumbalk North",
                "Burramboot",
                "Wirrate",
                "Weatherboard",
                "Ballangeich",
                "Agnes",
                "Chapel Flat",
                "Swan Bay",
                "Gladysdale",
                "Eltham North",
                "Ivanhoe",
                "Majorca",
                "Gisborne South",
                "Zeerust",
                "Nulla Vale",
                "Glendaruel",
                "Vectis",
                "Footscray",
                "Brunswick East",
                "Echuca East",
                "Tyrendarra",
                "Lovely Banks",
                "Wilsons Hill",
                "Bentleigh East",
                "Richmond North",
                "Barunah Park",
                "Poolaijelo",
                "Albion",
                "Highton",
                "Carrum",
                "Boolite",
                "Pearsondale",
                "The Honeysuckles",
                "Warrak",
                "Mysia",
                "Dunearn",
                "Howqua Hills",
                "Wantirna South",
                "Timor",
                "Tarnagulla",
                "Ailsa",
                "Porcupine Flat",
                "Wartook",
                "Moyston",
                "Loch Sport",
                "Happy Valley",
                "Tunstall Square Po",
                "Nichols Point",
                "Benloch",
                "Redesdale",
                "Northcote South",
                "Yabba North",
                "Bonnie Doon",
                "Greenhill",
                "Borung",
                "Larpent",
                "Tantaraboo",
                "Mepunga",
                "Avonmore",
                "Fiery Flat",
                "Caldermeade",
                "Pioneer Bay",
                "Burkes Bridge",
                "Colliver",
                "Springbank",
                "Glenlee",
                "Altona Meadows",
                "Wulgulmerang East",
                "Bundalaguah",
                "Koriella",
                "Yarrawonga",
                "Southern Cross",
                "Koonda",
                "Wild Dog Valley",
                "Separation Creek",
                "Wehla",
                "Musk",
                "Stratford",
                "Lysterfield",
                "Patho",
                "Croydon North",
                "Whipstick",
                "Homewood",
                "Newhaven",
                "Bullarto",
                "Delegate River",
                "Mordialloc North",
                "Oaklands Junction",
                "Telangatuk East",
                "Morwell Upper",
                "Great Western",
                "Auburn",
                "Launching Place",
                "Pilchers Bridge",
                "Boorhaman",
                "Melbourne",
                "St Kilda South",
                "Gorae",
                "Tyrrell",
                "Coonooer Bridge",
                "Mincha",
                "St Kilda Road Central",
                "Hepburn Springs",
                "Hopetoun Gardens",
                "Tootgarook",
                "Baromi",
                "Sebastopol",
                "Yarroweyah",
                "Natte Yallock",
                "Essendon",
                "Gainsborough",
                "Bradford",
                "Noble Park",
                "Carrajung South",
                "Brandon Park",
                "Epsom",
                "Caulfield North",
                "Merricks Beach",
                "Ebden",
                "Springmount",
                "Surrey Hills South",
                "Winton North",
                "Boneo",
                "Daisy Hill",
                "Yeodene",
                "Caulfield Junction",
                "Tarneit",
                "Bonbeach",
                "Milnes Bridge",
                "Cremorne",
                "Appin",
                "The Sisters",
                "Mount Taylor",
                "Officer South",
                "Bridge Creek",
                "Chetwynd",
                "Wentworth",
                "Carlyle",
                "Syndal",
                "Thorpdale South",
                "Drummond North",
                "Cheshunt",
                "Balliang",
                "Chewton Bushlands",
                "Dingley Village",
                "Leslie Manor",
                "Hawthorn North",
                "Balook",
                "Gembrook",
                "Surrey Hills",
                "Yarrambat",
                "Lockwood",
                "Blackheath",
                "Murrindal",
                "Harkness",
                "Moreland",
                "Lake Wellington",
                "Garvoc",
                "Hattah",
                "Blackwood Forest",
                "Glenormiston North",
                "Mckenzie Hill",
                "Glen Creek",
                "Armstrong",
                "Traralgon East",
                "Broken Creek",
                "Nullawarre North",
                "Heidelberg Rgh",
                "Muntham",
                "Rawson",
                "Rocklands",
                "Ferguson",
                "Litchfield",
                "Newlyn North",
                "Taminick",
                "St Albans",
                "Anakie",
                "Lancaster",
                "Arcadia South",
                "Hastings",
                "Edgecombe",
                "Langi Logan",
                "Horsham West",
                "Kooroocheang",
                "Worrowing",
                "Warragul South",
                "Woodend",
                "Corunnun",
                "Grovedale",
                "Glenaire",
                "Koornalla",
                "Tostaree",
                "Somerton Park",
                "Altona East",
                "Nar Nar Goon",
                "Thornhill Park",
                "Moormbool West",
                "Ashbourne",
                "Browns Plains",
                "Coral Bank",
                "Numurkah",
                "Yarrawonga South",
                "Williamstown North",
                "Campbells Forest",
                "Jungaburra",
                "Leongatha",
                "Concongella",
                "Blowhard",
                "Merrijig",
                "Charlemont",
                "Churchill",
                "Landsborough West",
                "Wonyip",
                "Childers",
                "Muckatah",
                "Wattle Hill",
                "Eaglehawk",
                "Newborough",
                "Melbourne University",
                "Lardner",
                "Long Gully",
                "Girgarre",
                "Sandhurst East",
                "Ascot Vale",
                "Glenferrie South",
                "East Warburton",
                "Lake Meran",
                "Carlton North",
                "Marungi",
                "Meatian",
                "Woodbrook",
                "Calder Park",
                "Lake Wendouree",
                "Yulecart",
                "Mount Dandenong",
                "Parkville",
                "Bandiana",
                "Curdies River",
                "Bald Hills",
                "Rosebud",
                "Edi",
                "Tatong",
                "Ivanhoe North",
                "Douglas",
                "Catumnal",
                "Kew East",
                "Armstrong Creek",
                "Barwite",
                "Westmeadows",
                "Gunyah",
                "Avoca",
                "Lang Lang",
                "Deepdene Dc",
                "Boort",
                "Mount Prospect",
                "Riverside",
                "Antwerp",
                "Taripta",
                "Werona",
                "Caulfield",
                "Bung Bong",
                "Tanwood",
                "St Germains",
                "Narre Warren",
                "Aspendale",
                "Nerrena",
                "Tom Groggin",
                "Yan Yean",
                "Hughesdale",
                "Glenhope",
                "Wangaratta West",
                "Balwyn East",
                "Whiteheads Creek",
                "Greens Creek",
                "Herne Hill",
                "Toora",
                "Sunbury",
                "Benwerrin",
                "Tandarook",
                "Mead",
                "Clydesdale",
                "Fawkner",
                "Pimpinio",
                "Mount Dryden",
                "Tenby Point",
                "Booran Road Po",
                "Cobram",
                "Leneva",
                "Balwyn",
                "Hume Weir",
                "Cope Cope",
                "Euroa",
                "Gipsy Point",
                "Wendouree Village",
                "Lindsay",
                "Oakleigh",
                "Warrandyte",
                "Little Desert",
                "Everton Upper",
                "Waggarandall",
                "Mount Mercer",
                "Fraser Rise",
                "North Warrandyte",
                "Cross Roads",
                "Barrys Reef",
                "Barooga",
                "Warrnambool",
                "Newport",
                "Whittington",
                "South Wharf",
                "Bonegilla",
                "Bo Peep",
                "Trentham",
                "Benalla West",
                "Healesville Main Street",
                "Gre Gre South",
                "Boorcan",
                "Bundalong South",
                "Moglonemby",
                "Lyal",
                "Grenville",
                "Forbes",
                "Fawcett",
                "Buln Buln",
                "Addington",
                "Samaria",
                "Frenchmans",
                "Mount Pleasant",
                "Maramingo Creek",
                "Hawkesdale",
                "Gerang Gerung",
                "Fairy Dell",
                "Mount Camel",
                "Gladstone Park",
                "Trafalgar East",
                "Albanvale",
                "Kingsville",
                "Blackwood",
                "Lima",
                "Gowar East",
                "Lake Lonsdale",
                "Banyenong",
                "Buln Buln East",
                "Big Hill",
                "Blairgowrie",
                "Newcomb",
                "Kunyung",
                "Waterford Park",
                "Swanwater",
                "Moggs Creek",
                "Alberton",
                "Millgrove",
                "South Geelong",
                "Tabberabbera",
                "Bostocks Creek",
                "Moonlight Flat",
                "Lima South",
                "Keysborough",
                "Banyule",
                "Drouin South",
                "Bullarto South",
                "Gowanbrae",
                "Jung",
                "Fulham",
                "Thomastown",
                "Bakery Hill",
                "Upper Gundowring",
                "Dysart",
                "Wuk Wuk",
                "Watsonia North",
                "Brentford Square",
                "Weeaproinah",
                "Altona",
                "West Footscray",
                "Powlett River",
                "Point Leo",
                "Trafalgar",
                "Ashburton",
                "Buchan South",
                "Moorooduc",
                "Cotham",
                "Marthavale",
                "Dry Diggings",
                "Benarch",
                "Silver Creek",
                "Nagambie",
                "Hallston",
                "Ghin Ghin",
                "Rosanna",
                "Shallow Inlet",
                "Killawarra",
                "Bendoc",
                "Angip",
                "Bullengarook",
                "South Melbourne Dc",
                "Wangandary",
                "Millbrook",
                "Brunswick South",
                "North Wonthaggi",
                "Warncoort",
                "Warrenmang",
                "Ross Creek",
                "Miepoll",
                "Kulwin",
                "Wyelangta",
                "Greensborough",
                "Boweya North",
                "Kinglake",
                "Kilsyth",
                "Eppalock",
                "Nandaly",
                "Mudgegonga",
                "Berrimal West",
                "Ruffy",
                "Yabba South",
                "Melton",
                "Strathlea",
                "Springfield",
                "Kialla East",
                "Teal Point",
                "Box Hill South",
                "Casterton",
                "Dalmore",
                "Ancona",
                "Alfredton",
                "Echuca Village",
                "Gredgwin",
                "Trawool",
                "Arnold",
                "North Bendigo",
                "Ocean Grove",
                "Colac East",
                "Englefield",
                "Mitchells Hill",
                "Coalville",
                "Fryerstown",
                "Barjarg",
                "Tooradin",
                "Mont Albert North",
                "Newborough East",
                "Nutfield",
                "Kennett River",
                "Mena Park",
                "Bethanga",
                "Narre Warren East",
                "Epping Dc",
                "Indigo",
                "Hampton North",
                "Torwood",
                "Keely",
                "Shelley",
                "Burrumbeet",
                "Buchan",
                "Mount Toolebewong",
                "Capel Sound",
                "Glen Iris",
                "Ocean Grange",
                "Moranding",
                "Sale",
                "St Arnaud East",
                "Myola",
                "Hampton",
                "Broughton",
                "Carron",
                "Swan Hill",
                "Allestree",
                "Yalmy",
                "Ararat East",
                "South Yarra",
                "Wonnangatta",
                "Lamplough",
                "Allambee South",
                "Bungador",
                "Woorarra",
                "Broadmeadows",
                "Won Wron",
                "Main Lead",
                "Devon Meadows",
                "Wangarabell",
                "Noradjuha",
                "Hawthorn",
                "Timboon",
                "Cloverlea",
                "Bannockburn",
                "Hunterston",
                "Cambrian Hill",
                "Barraport West",
                "Remlaw",
                "Dunnstown",
                "Dimboola",
                "Kyneton",
                "Brucknell",
                "Traralgon South",
                "Langsborough",
                "Sandhill Lake",
                "Bimbourie",
                "Dobie",
                "Haven",
                "Murray-Sunset",
                "Were Street Po",
                "Staghorn Flat",
                "Wando Bridge",
                "Surrey Hills North",
                "Sunderland Bay",
                "Anglesea",
                "Wattle Flat",
                "Girgarre East",
                "Gannawarra",
                "North Wangaratta",
                "Eastern View",
                "Jericho",
                "Darkbonee",
                "Williamstown",
                "Balaclava",
                "Portland North",
                "Goon Nure",
                "Myrtlebank",
                "Little Hampton",
                "Billabong",
                "Crossover",
                "Mooroolbark",
                "Winnindoo",
                "Hampton Park",
                "Poowong East",
                "Warracknabeal",
                "Winter Valley",
                "Kangaroo Flat",
                "Canary Island",
                "Tanjil",
                "Cranbourne North",
                "Elsternwick",
                "Keilor Downs",
                "Creswick North",
                "Longwood East",
                "Green Lake",
                "Great Southern",
                "Harston",
                "Ballarat North",
                "Mandurang South",
                "Bungalally",
                "Wangaratta Forward",
                "Mitcham North",
                "Upton Hill",
                "Lake Tyrrell",
                "Leichardt",
                "Hesket",
                "Waterholes",
                "Dean",
                "Ingliston",
                "Parwan",
                "Grovedale East",
                "Walhalla East",
                "Flynn",
                "Toorak",
                "Whitelaw",
                "Mooroopna",
                "Moorilim",
                "Yandoit Hills",
                "Donvale",
                "Edi Upper",
                "Undera",
                "Eltham",
                "Taroon",
                "Goldie",
                "Wooragee",
                "Heathcote South",
                "Pinewood",
                "Gooram",
                "Bengworden",
                "Tyaak",
                "Garfield North",
                "Southbank",
                "Talgarno",
                "Oxley",
                "Gilderoy",
                "High Camp",
                "Gobarup",
                "Mildura East",
                "Mildura West",
                "Robertsons Beach",
                "Warrion",
                "Caulfield South",
                "Langi Kal Kal",
                "Framlingham East",
                "Derrimut",
                "Yarraberb",
                "Cosgrove",
                "Merriang South",
                "Mountain Gate",
                "Powelltown",
                "Longford",
                "Ivanhoe East",
                "Cooma",
                "Doncaster",
                "Kawarren",
                "Scoresby",
                "Bookaar",
                "Strathdownie",
                "Woodstock",
                "King Valley",
                "Macks Creek",
                "Nathalia",
                "Gooramadda",
                "Ecklin South",
                "Merbein",
                "Rochford",
                "Mirboo North",
                "Berriwillock",
                "Eildon",
                "Mildura Centre Plaza",
                "Kerang East",
                "Porepunkah",
                "Abbeyard",
                "Carboor",
                "Wombat Creek",
                "Neerim Junction",
                "Windsor",
                "Cheltenham East",
                "Gisborne",
                "Baarmutha",
                "Ballan",
                "Biggara",
                "Mitre",
                "Wallup",
                "Mount Egerton",
                "Mount Lonarch",
                "Keilor Park",
                "Muskerry East",
                "Cromer",
                "Cobram East",
                "Baynton",
                "Yelta",
                "Mount Wallace",
                "Alphington",
                "Lemnos",
                "Woodstock West",
                "Rich Avon East",
                "Wonwondah South",
                "Newbury",
                "Bentleigh",
                "Tabilk",
                "Boho South",
                "Oak Park",
                "Somerville",
                "Dutson",
                "Glengala",
                "Avalon",
                "Bridge Inn",
                "Golden Gully",
                "Yarra Junction",
                "Guys Hill",
                "Delacombe",
                "Gateway Island",
                "Deddick Valley",
                "Heathmere",
                "Hotham Hill",
                "Diamond Hill",
                "Kalkallo",
                "Grahamvale",
                "Rosewhite",
                "Yambuk",
                "Pakenham South",
                "Main Ridge",
                "Hallora",
                "Ballarat",
                "Colac",
                "Fern Hill",
                "Wareek",
                "Cottles Bridge",
                "Chapel Street North",
                "Red Hill South",
                "Frankston",
                "Poowong North",
                "Bravington",
                "Studfield",
                "Gooroc",
                "Carlton",
                "Box Hill North",
                "Hillside",
                "Mount Cameron",
                "Morwell East",
                "Tysons Reef",
                "Granite Rock",
                "Pigeon Ponds",
                "Mount Beauty",
                "Lake Hume Village",
                "Paaratte",
                "Rhymney",
                "Tanybryn",
                "Bellbridge",
                "Wyuna",
                "Patterson",
                "Craigieburn",
                "Kergunyah South",
                "Pirron Yallock",
                "Westby",
                "Foster",
                "Lockwood South",
                "Willung",
                "Hawkhurst",
                "Snake Valley",
                "Docklands",
                "Derrinal",
                "Lakes Entrance",
                "Waygara",
                "Miga Lake",
                "Woolshed Flat",
                "Jilpanger",
                "Glen Huntly",
                "Bungaree",
                "Whitlands",
                "Wishart",
                "Black Hill",
                "Congupna",
                "Loch Valley",
                "Lalor Plaza",
                "Coghills Creek",
                "Mount Napier",
                "North Melbourne",
                "Reservoir North",
                "Wulgulmerang",
                "Emu Creek",
                "Warragul West",
                "Walkerville North",
                "Clyde North",
                "Athlone",
                "Seddon West",
                "Woodvale",
                "Buffalo",
                "Warranwood",
                "Tarcombe",
                "Tamleugh",
                "Hmas Cerberus",
                "Gerangamete",
                "Catani",
                "Upotipotpon",
                "Wool Wool",
                "Valencia Creek",
                "Duchembegarra",
                "Boorhaman East",
                "Walhalla",
                "Mitcham",
                "Ardeer",
                "Sailors Falls",
                "Mittyack",
                "Mountain Bay",
                "Howqua Inlet",
                "Caniambo",
                "Sunshine North",
                "Bayles",
                "Tooan",
                "Piedmont",
                "Jallumba",
                "Tonimbuk",
                "Sailors Hill",
                "Laen North",
                "Curlewis",
                "Boole Poole",
                "Lone Pine",
                "Mirboo",
                "Merrimu",
                "Montmorency",
                "Bendigo",
                "Strzelecki",
                "Darley",
                "Huntly",
                "Heidelberg",
                "Upper Lurg",
                "Harkaway",
                "Reedy Lake",
                "Dahlen",
                "Iona",
                "Hotham Heights",
                "Pentland Hills",
                "Corio",
                "Howqua",
                "Carrajung Lower",
                "Craigie",
                "Marshall",
                "Bael Bael",
                "Clayton",
                "Manns Beach",
                "Neerim North",
                "Corringle",
                "Alberton West",
                "Belmont",
                "Sassafras",
                "Rangeview",
                "Lucas",
                "Carngham",
                "Allansford",
                "Lauriston",
                "Somers",
                "Barwidgee",
                "Colbinabbin",
                "Metcalfe East",
                "Buffalo River",
                "Lansell Plaza",
                    "Brimboal",
                    "Dendy",
                    "Toombon",
                    "Creek View",
                    "Blackburn South",
                    "Bathumi",
                    "Wemen",
                    "Mount Best",
                    "Bowenvale",
                    "Wallan East",
                    "Mambourin",
                    "The Basin",
                    "Wattle Park",
                    "Williams Landing",
                    "Hiamdale",
                    "Lalor",
                    "Buckley",
                    "Langwarrin",
                    "Mount Cole",
                    "Glenburn",
                    "Thaloo",
                    "Lerderderg",
                    "Healesville",
                    "Butchers Ridge",
                    "Endeavour Hills",
                    "St Kilda",
                    "Mossiface",
                    "Waverley Gardens",
                    "Delatite",
                    "Sea Lake",
                    "Silverleaves",
                    "Glenaroua",
                    "Dadswells Bridge",
                    "Cannons Creek",
                    "Seddon",
                    "Crymelon",
                    "Cardinia",
                    "Yapeen",
                    "Woorarra East",
                    "Knockwood",
                    "Doveton",
                    "Caringal",
                    "Moe",
                    "Raglan",
                    "Dandenong South",
                    "Balnarring Beach",
                    "Kilfeera",
                    "Chirnside Park",
                    "Warrandyte South",
                    "Berwick",
                    "Mitta Mitta",
                    "Camperdown",
                    "Richmond East",
                    "Karingal Centre",
                    "Waurn Ponds",
                    "Londrigan",
                    "Moolap",
                    "Buckland",
                    "Gillum",
                    "Buninyong",
                    "Quambatook",
                    "Bittern",
                    "Laang",
                    "Jack River",
                    "Iguana Creek",
                    "Cherokee",
                    "Truganina",
                    "Seabrook",
                    "Tower Hill",
                    "Portland West",
                    "Hoppers Crossing",
                    "Youarang",
                    "Zumsteins",
                    "Yering",
                    "Yeo",
                    "Simpson",
                    "Doreen",
                    "Koonwarra",
                    "Beazleys Bridge",
                    "Toongabbie",
                    "Barkly",
                    "Balmattum",
                    "Freeburgh",
                    "Sarsfield",
                    "Bangholme",
                    "Harmers Haven",
                    "Mount Burnett",
                    "Mepunga East",
                    "Carrajung",
                    "Eversley",
                    "Eynesbury",
                    "Wahgunyah",
                    "Wodonga",
                    "Bend Of Islands",
                    "Darlimurla",
                    "Caveat",
                    "Wombelano",
                    "Smiths Gully",
                    "Daltons Bridge",
                    "Hilldene",
                    "Hill End",
                    "Mount Hotham",
                    "Sedgwick",
                    "Pental Island",
                    "Irrewillipe",
                    "Bairnsdale",
                    "Norval",
                    "East Yeoburn",
                    "Lake Goldsmith",
                    "Macorna",
                    "Carapooee West",
                    "Warragul",
                    "Drumanure",
                    "Chartwell",
                    "Burnside",
                    "Wroxham",
                    "Upwey",
                    "Cohuna",
                    "Malvern",
                    "Altona North",
                    "Pier Milan",
                    "Barongarook",
                    "Taylors Lakes",
                    "Portsea",
                    "Argyle",
                    "Telford",
                    "Queenscliff",
                    "Nurran",
                    "Koroop",
                    "Bellfield",
                    "Beaconsfield",
                    "Newlands Arm",
                    "Allambee",
                    "Mcmahons Creek",
                    "Torquay",
                    "Appin South",
                    "Mortchup",
                    "Lexton",
                    "Murmungee",
                    "Llanelly",
                    "Leopold",
                    "Christmas Hills",
                    "Ledcourt",
                    "Petticoat Creek",
                    "Saint Helena",
                    "Runnymede",
                    "Corindhap",
                    "Mount Helen",
                    "Brewster",
                    "Tarago",
                    "Toolondo",
                    "Healesville Post Shop",
                    "Tallarook",
                    "Rosebrook",
                    "Graytown",
                    "Gelliondale",
                    "Glen Falloch",
                    "Elingamite North",
                    "Callignee North",
                    "Gong Gong",
                    "Cobblebank",
                    "Chum Creek",
                    "Bahgallah",
                    "Brimpaen",
                    "East Melbourne",
                    "Greta West",
                    "Tallandoon",
                    "Boolarong",
                    "Sailors Gully",
                    "Travancore",
                    "Dandenong East",
                    "Middle Tarwin",
                    "Foster North",
                    "Clyde",
                    "Springvale South",
                    "Horsham",
                    "Fernvale",
                    "Montgomery",
                    "Caroline Springs",
                    "Osbornes Flat",
                    "Creswick",
                    "Bennettswood",
                    "Nine Mile",
                    "Clonbinane",
                    "Scotsburn",
                    "Bolwarra",
                    "Cambarville",
                    "Kerrisdale",
                    "Sunset Strip",
                    "Upper Plenty",
                    "Wallan",
                    "Tecoma",
                    "Wattle Creek",
                    "Mansfield",
                    "Wilsons Promontory",
                    "Tuerong",
                    "Goongerah",
                    "Neereman",
                    "Bridgewater North",
                    "Macclesfield",
                    "Seaview",
                    "Nullawarre East",
                    "Wongungarra",
                    "Spargo Creek",
                    "Jeffcott North",
                    "Swanwater West",
                    "Meeniyan",
                    "Carpendeit",
                    "Muskerry",
                    "Cora Lynn",
                    "Thomson",
                    "Irishtown",
                    "Joyces Creek",
                    "Kurraca",
                    "Marcus Hill",
                    "Wal Wal",
                    "Moyreisk",
                    "Kangaroo Ground",
                    "Strath Creek",
                    "W Tree",
                    "Long Forest",
                    "Brunswick Lower",
                    "Invergordon South",
                    "Pranjip",
                    "Snake Island",
                    "Preston West",
                    "Wonga Park",
                    "Bete Bolong North",
                    "Grantville",
                    "Moriac",
                    "Bundoora",
                    "Chepstowe",
                    "Preston",
                    "Glenluce",
                    "Vervale",
                    "Weerite",
                    "Dooboobetic",
                    "Brumby",
                    "Allambee Reserve",
                    "Gheringhap",
                    "Quantong",
                    "Swan Island",
                    "Longlea",
                    "Illowa",
                    "Norlane",
                    "Williams Raaf",
                    "Old Tallangatta",
                    "Ferntree Gully",
                    "Moonee Vale",
                    "Wandin East",
                    "Crooked River",
                    "Meerlieu",
                    "Croydon Hills",
                    "Jacana",
                    "Tanjil Bren",
                    "Dunkirk",
                    "Pira",
                    "Morwell",
                    "Speewa",
                    "Bendigo South",
                    "Coomboona",
                    "Specimen Hill",
                    "Carapooee",
                    "Broadford",
                    "Lawler",
                    "Tolmie",
                    "Kingsville West",
                    "Bobinawarrah",
                    "Grey River",
                    "Hurstbridge",
                    "Avon Plains",
                    "Gre Gre North",
                    "Cornella",
                    "Kilsyth South",
                    "Port Albert",
                    "Spring Gully",
                    "Wallagaraugh",
                    "Labertouche",
                    "Sargood",
                    "North Road",
                    "Murrumbeena",
                    "Gower",
                    "Freshwater Creek",
                    "Venus Bay",
                    "Walkerville South",
                    "Bungil",
                    "Strathfieldsaye",
                    "Elwood",
                    "Reedy Creek",
                    "Myrniong",
                    "Baringhup West",
                    "Steiglitz",
                    "Lorne",
                    "Smokeytown",
                    "Tynong",
                    "Shelford",
                    "East Geelong",
                    "Illabarook",
                    "Invermay Park",
                    "Cashmore",
                    "Arthurs Seat",
                    "Yielima",
                    "Kallista",
                    "Lethbridge",
                    "Moonambel",
                    "Callawadda",
                    "St Andrews Beach",
                    "Licola",
                    "Yuroke",
                    "Winjallok",
                    "Glenrowan",
                    "Denison",
                    "Castle Creek",
                    "Box Hill Central",
                    "Baynton East",
                    "Baxter",
                    "Macedon",
                    "Appin Park",
                    "Byawatha",
                    "Crookayan",
                    "Leigh Creek",
                    "Laceby",
                    "Bringenbrong",
                    "Seacombe",
                    "Orrvale",
                    "Mount Martha",
                    "Abbotsford",
                    "Tallygaroopna",
                    "Attwood",
                    "Hamilton",
                    "Brodribb River",
                    "Kialla",
                    "Brimin",
                    "Omeo Valley",
                    "Murrabit West",
                    "Noble Park East",
                    "Aberfeldy",
                    "Alexandra",
                    "Whoorel",
                    "White Hills",
                    "Eganstown",
                    "Sylvester",
                    "Barfold",
                    "Upper Ferntree Gully",
                    "Staffordshire Reef",
                    "Maribyrnong",
                    "Cape Otway",
                    "Wendouree",
                    "Tesbury",
                    "Pomonal",
                    "Wangaratta",
                    "Seaholme",
                    "Toolome",
                    "Churchill Island",
                    "Mepunga West",
                    "Mont Albert",
                    "Mount Cottrell",
                    "Frankston South",
                    "Kelvin View",
                    "Lake Fyans",
                    "Koroit",
                    "Yannathan",
                    "Belgrave South",
                    "Koallah",
                    "Invergordon",
                    "Moorngag",
                    "Brighton Road",
                    "Wandin North",
                    "Smythes Creek",
                    "Stanley",
                    "Bannerton",
                    "Tyrrell Downs",
                    "Echuca West",
                    "Wandown",
                    "Leonards Hill",
                    "Darriman",
                    "Shady Creek",
                    "Irrewarra",
                    "Yandoit",
                    "Wattville",
                    "Benayeo",
                    "Port Melbourne",
                    "Essendon Fields",
                    "Wattle Bank",
                    "Kensington",
                    "Heathmont",
                    "Boorool",
                    "Winslow",
                    "Cherrypool",
                    "Lake Boga",
                    "Boho",
                    "Kiewa",
                    "Towong",
                    "Drouin",
                    "Surf Beach",
                    "Moolort",
                    "Sherbrooke",
                    "Goughs Bay",
                    "Avenel",
                    "Havelock",
                    "Rhyll",
                    "Tatura",
                    "Glenrowan West",
                    "Henty",
                    "Bridgewater On Loddon",
                    "Balliang East",
                    "Ringwood",
                    "Prahran",
                    "Gelantipy",
                    "Rumbug",
                    "Budgerum East",
                    "Vesper",
                    "Research",
                    "Alma",
                    "Connewarre",
                    "Barraport",
                    "Howes Creek",
                    "Point Cook",
                    "Eastville",
                    "Selby",
                    "Ayrford",
                    "Willenabrina",
                    "Macleod West",
                    "St Helens",
                    "West Melbourne",
                    "Franklinford",
                    "Bona Vista",
                    "Greenvale",
                    "Cabanandra",
                    "Gillieston",
                    "Tamleugh North",
                    "Drung",
                    "Scotchmans Lead",
                    "Campaspe West",
                    "Mannerim",
                    "South Morang",
                    "Barkstead",
                    "Gunbower",
                    "Clarendon",
                    "Birdwoodton",
                    "Red Hill",
                    "Cape Conran",
                    "Longwarry",
                    "Nuggetty",
                    "Tubbut",
                    "Fawkner North",
                    "Gladfield",
                    "Elberton",
                    "Portland",
                    "Perry Bridge",
                    "Myrtle Creek",
                    "Tinamba",
                    "Cobrico",
                    "Ballarat Central",
                    "Mcmillans",
                    "Plumpton",
                    "Cranbourne South",
                    "Hazelwood South",
                    "Metung",
                    "Stawell",
                    "Monbulk",
                    "Korobeit",
                    "Drummond",
                    "Coatesville",
                    "Bulga",
                    "Polisbet",
                    "Axe Creek",
                    "Merricks North",
                    "Koo Wee Rup",
                    "Coragulac",
                    "Shepparton North",
                    "Westbury",
                    "Rosebud Plaza",
                    "Bunyip North",
                    "Tylden South",
                    "Esmond",
                    "Clifton Creek",
                    "Armadale North",
                    "Chocolyn",
                    "Ballarat East",
                    "Mornington",
                    "Middle Park",
                    "Erica",
                    "Rye",
                    "Woolshed",
                    "Gilberton",
                    "Wrixon",
                    "Bringalbert",
                    "Claretown",
                    "Woodfield",
                    "Sawmill Settlement",
                    "Killarney",
                    "Allans Flat",
                    "Shepparton East",
                    "Beenak",
                    "Maddingley",
                    "Perkins Reef",
                    "Rosedale",
                    "Maryborough",
                    "Ryans",
                    "Woodglen",
                    "Lower Plenty",
                    "Myers Flat",
                    "Whanregarwen",
                    "Guthridge",
                    "Bunbartha",
                    "Lang Lang East",
                    "Scarsdale",
                    "Moorabool",
                    "Hawthorn West",
                    "Joel Joel",
                    "Falls Creek",
                    "Barkers Creek",
                    "Morgiana",
                    "Blampied",
                    "Koorlong",
                    "Braybrook",
                    "Glendonnell",
                    "Wyuna East",
                    "Murchison East",
                    "Wonwondah",
                    "Fentons Creek",
                    "Jordanville",
                    "Wahring",
                    "Minto",
                    "Walmer",
                    "Burnside Heights",
                    "Kanya",
                    "Simson",
                    "Redbank",
                    "Three Bridges",
                    "Mininera",
                    "Melbourne Airport",
                    "Geelong West",
                    "Strathkellar",
                    "Prahran East",
                    "Heidelberg Heights",
                    "Lorquon",
                    "Boronia",
                    "Tambo Upper",
                    "Wensleydale",
                    "Christies",
                    "Fernihurst",
                    "Waanyarra",
                    "Sassafras Gully",
                    "Corndale",
                    "Brandy Creek",
                    "Arthurs Creek",
                    "Clarinda",
                    "Boisdale",
                    "Dookie",
                    "Kariah",
                    "Modella",
                    "Moolerr",
                    "Cannum",
                    "Laverton",
                    "Limonite",
                    "Robinson",
                    "Morang South",
                    "Cabbage Tree",
                    "Mount Eliza",
                    "Longwarry North",
                    "Dreeite",
                    "Darling South",
                    "Hiawatha",
                    "Ultima East",
                    "Vermont",
                    "Wallaloo East",
                    "Berrys Creek",
                    "Bunding",
                    "Romsey",
                    "Ashwood",
                    "New Gisborne",
                    "Avondale Heights",
                    "Pitfield",
                    "Ravenswood South",
                    "Oakleigh East",
                    "Tylden",
                    "Mount Cole Creek",
                    "Yendon",
                    "Nariel Valley",
                    "Wabonga",
                    "Korweinguboora",
                    "Adams Estate",
                    "Jeeralang",
                    "Strathtulloh",
                    "Lake Buloke",
                    "Pine Lodge",
                    "Swan Marsh",
                    "Dreeite South",
                    "Jancourt",
                    "Pomborneit East",
                    "Mologa",
                    "Hazeldene",
                    "Rokeby",
                    "Tatura East",
                    "Wallington",
                    "Toolamba",
                    "Lake Mokoan",
                    "Black Range",
                    "Stockyard Hill",
                    "Mount Macedon",
                    "Goornong",
                    "Dallas",
                    "Ballarat Roadside Delivery",
                    "Cheltenham North",
                    "Boigbeat",
                    "Ormond",
                    "Olinda",
                    "Timbarra",
                    "St Kilda East",
                    "South Kingsville",
                    "Glomar Beach",
                    "Reynard",
                    "Tarwin East",
                    "St Andrews",
                    "Middle Camberwell",
                    "Badger Creek",
                    "Durdidwarrah",
                    "Strangways",
                    "Malvern East",
                    "Elingamite",
                    "Cowwarr",
                    "Knox City Centre",
                    "Mooroopna North West",
                    "Genoa",
                    "Germania",
                    "Glenfyne",
                    "Mount Eccles South",
                    "Frankston North",
                    "Rossbridge",
                    "Markwood",
                    "Maffra West Upper",
                    "Warrock",
                    "Lah",
                    "Brunswick",
                    "Kurraca West",
                    "Kolora",
                    "Warrenheip",
                    "Dereel",
                    "Shays Flat",
                    "Guildford",
                    "Garibaldi",
                    "Gre Gre",
                    "Chiltern",
                    "Brighton",
                    "Kalimna",
                    "Glengarry",
                    "Chillingollah",
                    "Keilor Lodge",
                    "Camberwell West",
                    "Giffard",
                    "Wangoom",
                    "Aubrey",
                    "Ovens",
                    "Riggs Creek",
                    "Rathscar West",
                    "Whittlesea",
                    "Harcourt North",
                    "Woodend North",
                    "Black Rock",
                    "Hicksborough",
                    "Lara",
                    "Pipers Creek",
                    "Sulky",
                    "Yuulong",
                    "Bolangum",
                    "Hazelwood",
                    "Yarragon South",
                    "Ravenhall",
                    "Ardmona",
                    "Goulburn Weir",
                    "Kialla West",
                    "Laverton Raaf",
                    "Deakin University",
                    "Curdie Vale",
                    "Slaty Creek",
                    "Willowmavin",
                    "Koorool",
                    "Painswick",
                    "Werribee South",
                    "Drouin West",
                    "Clear Lake",
                    "Wee Wee Rup",
                    "Bowser",
                    "Archerton",
                    "Beech Forest",
                    "Bright",
                    "Pastoria East",
                    "Piggoreet",
                    "Ripponlea",
                    "Cape Woolamai",
                    "Timor West",
                    "Edithvale",
                    "Nerrin Nerrin",
                    "Kennington",
                    "Warrayure",
                    "Beauchamp",
                    "Glendonald",
                    "Mount Beckworth",
                    "Wrathung",
                    "Wodonga Plaza",
                    "Chiltern Valley",
                    "Sutherlands Creek",
                    "Baranduda",
                    "Dingwall",
                    "Kilmore",
                    "Eureka",
                    "Bonshaw",
                    "Notting Hill",
                    "Noojee",
                    "Wargan",
                    "Corack",
                    "Cheltenham",
                    "Howitt Plains",
                    "Forge Creek",
                    "Barnadown",
                    "Chintin",
                    "Clunes",
                    "Wattle Glen",
                    "Terrick Terrick",
                    "Bendigo Forward",
                    "Vasey",
                    "Tyrendarra East",
                    "Tol Tol",
                    "Moonee Ponds",
                    "Collingwood North",
                    "Carapook",
                    "Mt Baw Baw",
                    "Kalimna West",
                    "Wallace",
                    "Nyarrin",
                    "Cape Paterson",
                    "Templestowe",
                    "Safety Beach",
                    "Amphitheatre",
                    "Colac West",
                    "Lucknow",
                    "Tarra Valley",
                    "Noorat",
                    "Lima East",
                    "Tarrington",
                    "Waterford",
                    "The Gurdies",
                    "Yawong Hills",
                    "Baringhup",
                    "Cape Bridgewater",
                    "Sunshine West",
                    "Yea",
                    "Bangerang",
                    "Nunawading",
                    "Gellibrand Lower",
                    "Mount Moriac",
                    "Mountain View",
                    "Mirimbah",
                    "Newry",
                    "Wy Yung",
                    "Keilor East",
                    "Northwood",
                    "Campbells Bridge",
                    "Wharparilla",
                    "Lake Eildon",
                    "Burnley North",
                    "Colac Colac",
                    "Newfield",
                    "Wimbledon Heights",
                    "West Creek",
                    "Drysdale",
                    "Nyerimilang",
                    "Rowsley",
                    "Wheatsheaf",
                    "Ascot",
                    "Dugays Bridge",
                    "Bulla",
                    "Rythdale",
                    "Waterways",
                    "Brunswick West",
                    "Stonyford",
                    "Yangery",
                    "Kanyapella",
                    "Staughton Vale",
                    "Milawa",
                    "Curdievale",
                    "Trawalla",
                    "Torrita",
                    "Leongatha North",
                    "Bulgana",
                    "Pastoria",
                    "Anderson",
                    "Victoria Gardens",
                    "Dixie",
                    "Knowsley",
                    "Dunrobin",
                    "Callignee",
                    "Mockinya",
                    "Mosquito Creek",
                    "Carrum Downs",
                    "Reservoir South",
                    "St Albans Park",
                    "St Kilda Road Melbourne",
                    "Nug Nug",
                    "South Purrumbete",
                    "Mordialloc",
                    "Kimbolton",
                    "South Dudley",
                    "Ninda",
                    "Bayswater North",
                    "Cairnlea",
                    "Quandong",
                    "Gentle Annie",
                    "Camberwell",
                    "Cocoroc",
                    "Katandra",
                    "Mulgrave",
                    "Cowleys Creek",
                    "Bruthen",
                    "Gorae West",
                    "Waldara",
                    "Muckleford",
                    "Campbellfield",
                    "Dooen",
                    "Kilmany",
                    "Taylor Bay",
                    "Skenes Creek",
                    "Wandana Heights",
                    "Paradise Beach",
                    "Bellarine",
                    "Yarraville",
                    "The Heart",
                    "Yallambie",
                    "Glenmaggie",
                    "Grassmere",
                    "Meadow Creek",
                    "Wonga",
                    "Narrawong",
                    "Cathcart",
                    "Malmsbury",
                    "Dromana",
                    "Navigators",
                    "Tarraville",
                    "Bambra",
                    "Cockatoo",
                    "Dennington",
                    "Nirranda East",
                    "Heytesbury Lower",
                    "Rowville",
                    "Sandhurst",
                    "Simmie",
                    "Paringi",
                    "Lance Creek",
                    "Croydon South",
                    "Normanville",
                    "Keilor",
                    "Dhurringile",
                    "Greta",
                    "Glenroy",
                    "Lillico",
                    "Golden Beach",
                    "Highlands",
                    "Bulleen South",
                    "Yatchaw",
                    "Macorna North",
                    "Mount Emu",
                    "Cannie",
                    "Bayswater",
                    "Darling",
                    "Warrong",
                    "Calrossie",
                    "Dumbalk",
                    "Patterson Lakes",
                    "Cardigan Village",
                    "Echuca South",
                    "Glen Park",
                    "Ullina",
                    "Briagolong",
                    "Crossley",
                    "Driffield",
                    "Fairfield",
                    "Trentham East",
                    "Molyullah",
                    "Moorabbin",
                    "Viewbank",
                    "Fingal",
                    "Ferndale",
                    "Tottington",
                    "Gundowring",
                    "West Wodonga",
                    "Fitzroy",
                    "Rose River",
                    "Munro",
                    "Springdallah",
                    "Scotsmans Lead",
                    "Menzies Creek",
                    "Willow Grove",
                    "Mccrae",
                    "Yallourn North",
                    "Lysterfield South",
                    "Mount Richmond",
                    "Amor",
                    "Yackandandah",
                    "Box Hill",
                    "Mollongghip",
                    "Haydens Bog",
                    "Sale North",
                    "Moorabbin East",
                    "Sydenham",
                    "Glenlyon",
                    "Framlingham",
                    "Wongarra",
                    "Yallourn",
                    "Murrabit",
                    "Walkerville",
                    "Leaghur",
                    "Kalkee",
                    "Byaduk North",
                    "Glen Waverley",
                    "Nurcoung",
                    "Newlyn",
                    "Windermere",
                    "Regent West",
                    "Gapsted",
                    "Hanging Rock",
                    "Yangoura",
                    "Wurdiboluc",
                    "Burramine",
                    "Clydebank",
                    "Cobbannah",
                    "Karramomus",
                    "Stradbroke",
                    "Flemington",
                    "Mount Bolton",
                    "Mount Tassie",
                    "Kobyboyn",
                    "Bailieston",
                    "Auburn South",
                    "Kevington",
                    "Gowangardie",
                    "Montrose",
                    "Mongans Bridge",
                    "Broomfield",
                    "Yarrowee",
                    "Fairley",
                    "Tyenna",
                    "Preston Lower",
                    "Kinglake West",
                    "Irymple",
                    "Mount Scobie",
                    "Ouyen",
                    "Lygon Street North",
                    "Westmere",
                    "Quarry Hill",
                    "Glengarry North",
                    "Hopetoun Park",
                    "Seaford",
                    "Cranbourne West",
                    "Fawkner East",
                    "Devils River",
                    "Balintore",
                    "Gordon",
                    "Lake Bunga",
                    "Yarpturk",
                    "Cobden",
                    "St Kilda West",
                    "Ravenswood",
                    "Icy Creek",
                    "Irrewillipe East",
                    "Puckapunyal Milpo",
                    "Houston",
                    "Waranga",
                    "St Arnaud",
                    "Hallam",
                    "Mount Buffalo",
                    "Narre Warren North",
                    "Wallinduc",
                    "Creighton",
                    "Ellinbank",
                    "Boonah",
                    "Bald Rock",
                    "Harcourt",
                    "Templestowe Lower",
                    "Eastwood",
                    "Rathscar",
                    "Giffard West",
                    "Mount Waverley",
                    "Poowong",
                    "Merbein South",
                    "Kerang",
                    "Kew",
                    "Avonsleigh",
                    "Dawson",
                    "Longerenong",
                    "Clayton South",
                    "Seville East",
                    "Learmonth",
                    "Smoko",
                    "Grangefields",
                    "Landsborough",
                    "Trida",
                    "Murroon",
                    "Stockdale",
                    "Murchison North",
                    "Boinka",
                    "Connangorach",
                    "Daylesford",
                    "Baw Baw",
                    "Rich Avon",
                    "Jacob Creek",
                    "Orford",
                    "Cullen",
                    "Tungamah",
                    "Acheron",
                    "Stonehaven",
                    "Woolamai",
                    "Bagshot",
                    "Rich Avon West",
                    "Smiths Beach",
                    "Vaughan",
                    "Emerald",
                    "Beechworth",
                    "Altona Gate",
                    "Flynns Creek",
                    "Woodstock On Loddon",
                    "Coopers Creek",
                    "Oxley Flats",
                    "Chelsea",
                    "Gil Gil",
                    "Richmond",
                    "Nalinga",
                    "Bellbrae",
                    "Echuca",
                    "Kerrimuir",
                    "Spotswood",
                    "Winchelsea South",
                    "Wattletree Road Po",
                    "Delburn",
                    "Gherang",
                    "Ercildoune",
                    "Paynesville",
                    "Canterbury",
                    "Bete Bolong",
                    "Flamingo Beach",
                    "Nowie",
                    "Strathmore",
                    "Apsley",
                    "Simpsons Creek",
                    "Arcadia",
                    "East Bairnsdale",
                    "Granya",
                    "Mardan",
                    "Murra Warra",
                    "Highpoint City",
                    "Tremont",
                    "Pound Creek",
                    "Tragowel",
                    "Dandenong North",
                    "Park Orchards",
                    "Myrtleford",
                    "Tyers",
                    "Mernda",
                    "Bulleen",
                    "Fairhaven",
                    "Ombersley",
                    "Sunshine",
                    "Stawell West",
                    "Castle Donnington",
                    "Nintingbool",
                    "Parkdale",
                    "Burramine South",
                    "Swanpool",
                    "Gnotuk",
                    "Strathdale",
                    "Wodonga Forward",
                    "Buffalo Creek",
                    "Colbrook",
                    "Mitchellstown",
                    "Clematis",
                    "Officer",
                    "Highett",
                    "Skibo",
                    "Coimadai",
                    "Netherby",
                    "Mewburn Park",
                    "Dandenong",
                    "Running Creek",
                    "Mid Valley",
                    "Bullarook",
                    "Bochara",
                    "Mickleham",
                    "Werribee",
                    "Sovereign Hill",
                    "Fumina",
                    "Lyndhurst",
                    "Costerfield",
                    "Nerring",
                    "Watsons Creek",
                    "Greythorn",
                    "Glenorchy",
                    "Dellicknora",
                    "Botanic Ridge",
                    "Point Lonsdale",
                    "Lurg",
                    "Glenfalloch",
                    "Alvie",
                    "Kergunyah",
                    "Dergholm",
                    "Pootilla",
                    "Kealba",
                    "Llowalong",
                    "Croxton East",
                    "Minhamite",
                    "Goomalibee",
                    "Swan Hill Pioneer",
                    "Straten",
                    "Martins Creek",
                    "Boola",
                    "Heathcote",
                    "Buxton",
                    "Delahey",
                    "Roxburgh Park",
                    "Homebush",
                    "Fosterville",
                    "Tynong North",
                    "Natimuk",
                    "Ballarat West",
                    "Koo Wee Rup North",
                    "Bonang",
                    "Narre Warren South",
                    "Thowgla Valley",
                    "Kellalac",
                    "Buragwonduc",
                    "Tarilta",
                    "Somerton",
                    "Yando",
                    "Tourello",
                    "Maude",
                    "Port Fairy",
                    "Huon Creek",
                    "Bellellen",
                    "San Remo",
                    "Pine View",
                    "Walpa",
                    "Bagshot North",
                    "Dutton Way",
                    "Beveridge",
                    "Mount Franklin",
                    "Boweya",
                    "Barongarook West",
                    "Yarram",
                    "Niddrie North",
                    "Ryanston",
                    "Gymbowen",
                    "Ellerslie",
                    "Mystic Park",
                    "Arnold West",
                    "Murray Downs",
                    "Narbethong",
                    "Ararat",
                    "Lake Tyers Beach",
                    "Apollo Bay",
                    "Flora Hill",
                    "Bullaharre",
                    "Barunah Plains",
                    "Rodborough",
                    "Loy Yang",
                    "Benjeroop",
                    "Albert Park",
                    "Kerrie",
                    "Yarrunga",
                    "Melwood",
                    "Winlaton",
                    "Nalangil",
                    "Coburg North",
                    "Soldiers Hill",
                    "Trafalgar South",
                    "Tarrengower",
                    "Yarragon",
                    "Keilor North",
                    "Violet Town",
                    "Camberwell East",
                    "Rutherglen",
                    "Camberwell South",
                "Mallan",
                "Woori Yallock",
                "Hidden Valley",
                "Winchelsea",
                "Aire Valley",
                "Tamleugh West",
                "Maintongoon",
                "She Oaks",
                "Minjah",
                "Hensley Park",
                "Skye",
                "Limestone",
                "Tarrawarra",
                "Fountain Gate",
                "Comet Hill",
                "Tallangatta South",
                "Percydale",
                "Barwon Downs",
                "Robinvale Irrigation District Section C",
                "Stuart Mill",
                "Hampton East",
                "Upper Ryans Creek",
                "Noble Park North",
                "Kancoona South",
                "Wedderburn Junction",
                "Tarwin Lower",
                "Barwon Heads",
                "Mount Evelyn",
                "Dutson Downs",
                "Kirwans Bridge",
                "Nayook",
                "Pines Forest",
                "Aintree",
                "Wangaratta South",
                "Ruby",
                "Tidal River",
                "Kithbrook",
                "Johanna",
                "Toolangi",
                "Corop",
                "Barnawartha North",
                "Wantirna",
                "Garfield",
                "Areegra",
                "Toorongo",
                "Belvedere Park",
                "Armadale",
                "Tinamba West",
                "Barramunga",
                "Kinglake Central",
                "Glengarry West",
                "Northcote",
                "Princes Hill",
                "Burwood East",
                "Batman",
                "Wail",
                "Hansonville",
                "Silvan",
                "Dorodong",
                "Bamawm Extension",
                "Boosey",
                "Puckapunyal",
                "Waterloo",
                "Golden Square",
                "Dollar",
                "Bridgewater",
                "Arbuckle",
                "Bolwarrah",
                "Bells Beach",
                "Woodford",
                "Hernes Oak",
                "Wyndham Vale",
                "Frankston Heights",
                "Heath Field",
                "Glengower",
                "North Blackwood",
                "Pomborneit",
                "Bogong",
                "Ninyeunook",
                "Wulgulmerang West",
                "Illawarra",
                "Adelaide Lead",
                "Paradise",
                "Codrington",
                "Tyntynder",
                "Brighton East",
                "Merlynston",
                "Tottenham",
                "Ferny Creek",
                "Puralka",
                "Thalloo",
                "Briar Hill",
                "La Trobe University",
                "Thologolong",
                "Brown Hill",
                "Kancoona",
                "Tyabb",
                "Donnybrook",
                "Patho West",
                "Blackburn",
                "Hordern Vale",
                "Greendale",
                "Pakenham Upper",
                "Marraweeney",
                "Kurunjang",
                "Woosang",
                "Boorhaman North",
                "Dandongadale",
                "Belgrave Heights",
                "Maiden Gully",
                "Carlsruhe",
                "Dederang",
                "Springvale",
                "Bonnie Brook",
                "Crowlands",
                "Nerrina",
                "Ellaswood",
                "Werneth",
                "Madalya",
                "Liparoo",
                "Coronet Bay",
                "California Gully",
                "Cadello",
                "Big Pats Creek",
                "Tulkara",
                "Pomborneit North",
                "Germantown",
                "Forest Hill",
                "Kotupna",
                "Junortoun",
                "Sylvaterre",
                "Mount Clear",
                "Strathbogie",
                "Orbost",
                "Yellingbo",
                "Lilydale",
                "East Bendigo",
                "Essendon North",
                "Coongulla",
                "Sugarloaf",
                "Devon North",
                "Granite Flat",
                "Lake Bolac",
                "Wilby",
                "Tamboritha",
                "Blackwarry",
                "Newington",
                "Woorarra West",
                "Seymour South",
                "Hadfield",
                "Korumburra South",
                "Minmindie",
                "Annuello",
                "Branditt",
                "Lake Eppalock",
                "Suggan Buggan",
                "Nungurner",
                "Capels Crossing",
                "Peechelba East",
                "Dixons Creek",
                "Docker",
                "Sheans Creek",
                "Kunat",
                "Boomahnoomoonah",
                "Cheshunt South",
                "Woods Point",
                "Pascoe Vale South",
                "Darnum",
                "Raymond Island",
                "Pascoe Vale",
                "Fumina South",
                "Toolamba West",
                "Ripplebrook",
                "Merbein West",
                "Deans Marsh",
                "Kooyong",
                "Cape Clear",
                "Mirboo South",
                "Castlemaine",
                "Goschen",
                "Ada",
                "Campbelltown",
                "Woolenook",
                "Jamieson",
                "Fiskville",
                "Naroghid",
                "Shelbourne",
                "Callignee South",
                "Preston South",
                "Murphys Creek",
                "Buckley Swamp",
                "Merricks",
                "Humevale",
                "Myall",
                "Nambrok",
                "Maldon",
                "Ironbark",
                "Beremboke",
                "Kooreh",
                "Winton",
                "Baw Baw Village",
                "South Melbourne",
                "Laanecoorie",
                "Grass Flat",
                "Yanac",
                "Clifton Springs",
                "Porcupine Ridge",
                "Marlo",
                "Bruces Creek",
                "Mokepilly",
                "Lyonville",
                "Robinvale Irrigation District Section E",
                "Seymour",
                "Cowes",
                "Nilma North",
                "Newtown",
                "Greta South",
                "Lower Norton",
                "Cudgee",
                "Nelse",
                "Nangeela",
                "Doncaster East",
                "Strathmore Heights",
                "Killara",
                "Mount Rowan",
                "Hepburn",
                "Tyntynder South",
                "Ondit",
                "Coomoora",
                "Taylors Hill",
                "Inverloch",
                "Pearcedale",
                "Reservoir",
                "Langdons Hill",
                "Mount Buller",
                "Enochs Point",
                "Powers Creek",
                "East Wangaratta",
                "Richmond South",
                "Wingan River",
                "Bedford Road",
                "Killingworth",
                "Berrimal",
                "Deepdene",
                "Ben Nevis",
                "Budgee Budgee",
                "Toolleen",
                "Morrl Morrl",
                "The Patch",
                "St Leonards",
                "Tanjil South",
                "Haddon",
                "Turtons Creek",
                "Dargo",
                "Heatherton",
                "Yanakie",
                "Mildura South",
                "Langwarrin South",
                "Bunyip",
                "Havilah",
                "Maryvale",
                "Derby",
                "Fernshaw",
                "Havillah",
                "Bunkers Hill",
                "Eden Park",
                "Jindivick",
                "Wildwood",
                "Golden Point",
                "Marysville",
                "Five Ways",
                "Kingsbury",
                "Heidelberg West",
                "Medlyn",
                "Hazelwood North",
                "Burwood Heights",
                "Molka",
                "Faraday",
                "Selwyn",
                "Miners Rest",
                "Merton",
                "Mount Duneed",
                "Manifold Heights",
                "Berringama",
                "Beaufort",
                "Koorooman",
                "Belgrave",
                "Wedderburn",
                "Glenmore",
                "Mount Major",
                "Redcastle",
                "Willatook",
                "Timboon West",
                "Little River",
                "Gruyere",
                "Allendale",
                "Naring",
                "Riachella",
                "Roses Gap",
                "Brighton North",
                "Nangana",
                "Castella",
                "Mount Alfred",
                "Rokewood Junction",
                "Nuntin",
                "Moroka",
                "Garden City",
                "Macs Cove",
                "Robinvale",
                "Hoddles Creek",
                "Lochend",
                "Rostron",
                "Blackburn North",
                "Tullamarine",
                "Oakleigh South",
                "Kyneton South",
                "Gonn Crossing",
                "Mentone",
                "Corack East",
                "Balmoral",
                "Everton",
                "Weir Views",
                "Tahara",
                "Eskdale",
                "Sunday Creek",
                "Sandown Village",
                "Reefton",
                "Dalyston",
                "Willung South",
                "Kilmore East",
                "Benalla",
                "Diggers Rest",
                "Flaggy Creek",
                "Cooriemungle",
                "Lynbrook",
                "Wonthaggi",
                "Cabarita",
                "Jan Juc",
                "Cape Schanck",
                "Noorat East",
                "West Bendigo",
                "Dockers Plains",
                "St Helena",
                "Glenbrae",
                "Mount Bruno",
                "Portarlington",
                "Dropmore"
            )
            val outList = ArrayList<SearchListItem>()
            for(i in 0..list.size -1){
                val seachList = SearchListItem(i,list[i])
                outList.add(seachList)
            }
            return outList
        }
    }
}

